// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import Header from "@/components/header";
export const metadata: Metadata = {
  title: "React Shop",
  description: "Simple product listing with Next.js & Tailwind",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <Header />

        <main className="p-6">{children}</main>

        <footer className="mt-10 text-center text-sm text-gray-500 py-6 border-t">
          © 2025 E-Shop. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
